Software engineer at [Hakimo](https://www.hakimo.ai), in Bangalore. TypeScript and React at the
front, Python and Flask behind it — most of my time goes to the parts that run unattended.

<table>
<tr><td><b>Unattended systems</b></td><td>Queues, workers and scheduled paths — the code that fails hours after the thing that caused it, with nobody watching.</td></tr>
<tr><td><b>Product surfaces</b></td><td>React and TypeScript interfaces people use daily, wired end to end through the API and data model behind them.</td></tr>
<tr><td><b>Verification</b></td><td>Gates and tests cheap enough to run on every change, instead of once before a release.</td></tr>
</table>

### Work

[![portfolio-site — a static portfolio that ships zero runtime JavaScript, with 28 Playwright tests holding contrast, keyboard order and the no-JavaScript path across both themes. Astro, TypeScript, Playwright, Cloudflare.](assets/card-portfolio.svg)](https://github.com/Abhishek47v/portfolio-site)

<details>
<summary>&nbsp;&nbsp;What it looks like, and what holds it up</summary>

<br>

The sky is the page's ground, and the theme chooses which hours you are visiting. Day and night
are two authored palettes, not an inversion — so the illustration is the same drawing lit twice.

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/Abhishek47v/Abhishek47v/main/assets/site-dark.png">
  <img src="assets/site-light.png" width="700" alt="The portfolio's first screen: an illustrated sky over ridges, with the name set large in a serif face.">
</picture>

Every colour in the project lives in one file. A gate fails the build if a hex literal appears
anywhere else, which is what makes retuning the whole day a single-file change. Nothing renders
that depends on JavaScript — remove it and the site still reads and navigates.

That claim is only worth anything if something checks it, so four gates run on every change:

![A run of npm run verify in portfolio-site, all four gates passing: astro check, 46 files, 0 errors; tokens gate, no colour literal outside tokens.css; astro build, 2 pages in 1.45s; playwright, 28 passed in 21.5s.](assets/verify-gates.svg)

`docs/decisions.md` in that repo records what was rejected and why, which is the most useful file in it.

</details>

[![QuipWire — a social app whose real-time messaging keeps presence, delivery and seen receipts correct across two connected clients and a page reload. React, Express, MongoDB, Socket.IO.](assets/card-quipwire.svg)](https://github.com/Abhishek47v/QuipWire-social-media-web)

<details>
<summary>&nbsp;&nbsp;The part that was actually hard</summary>

<br>

Posts, follows and threaded replies are the easy half. The messaging path is not: the same
conversation has to stay correct in two places at once.

- **Presence** is a `userId → socketId` map rebroadcast on every connect and disconnect, so the
  online set is right after a refresh rather than only after a fresh login.
- **Read receipts** are a two-step write — mark the unseen messages, then update the
  conversation's `lastMessage.seen`, then notify the sender on their own socket. That order is
  what stops the conversation list and the open thread disagreeing about the same message.
- **Auth** is a signed JWT in an `httpOnly` cookie, so the token is never reachable from client
  JavaScript.

Built in 2024, and it shows in places: scheduled posting exists as a component and an unused
`node-cron` dependency but was never wired to the model, and the Socket.IO origin is still
pinned to localhost.

</details>

[![Driver behaviour analysis — a classifier that flags unsafe driving from telemetry, packaged as a Flask service with a container image, Kubernetes manifests and a persistent volume for the trained model. Python, TensorFlow, Flask, Docker, Kubernetes.](assets/card-driver.svg)](https://github.com/Abhishek47v/Driver-behavior-analysis-cnn)

<details>
<summary>&nbsp;&nbsp;Why the deployment is the interesting part</summary>

<br>

Each row is one driver — age, experience, distraction level, drowsiness score, pulse, speed,
acceleration — labelled with an unsafe-behaviour flag. A spatial ConvNet classifies it.

The model is deliberately small; the point was getting it off a laptop. It ships as a container
image with a Compose file for local work and Kubernetes manifests for a cluster, including a
persistent volume so a trained model survives the pod that produced it.

Honest scope: the inputs are tabular, not images, so a gradient-boosted baseline is the right
comparison and this repo does not make it. No held-out metric is reported either — it is a
working pipeline rather than a benchmarked model.

</details>
<!--START_SECTION:activity-->
<!--END_SECTION:activity-->

[Portfolio](https://my-portfolio.iamabhishekverma.workers.dev) · [LinkedIn](https://www.linkedin.com/in/abhishek-v612/)

<sub>This README is rendered from <a href="README.md.tpl">a template</a>; the cards are generated by <a href="scripts/build-svg.mjs">one script</a> and gated in CI on 4:1 contrast against both GitHub themes.</sub>
